=== dotnet/docfx/schemas/v1.0/schema.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "id": "https://github.com/dotnet/docfx/schemas/v1.0/schema.json",
    "title": "DocFX document schema meta-schema",
    "definitions": {
        "schemaArray": {
            "type": "array",
            "minItems": 1,
            "items": { "$ref": "#/definitions/propertyObject" }
        },
        "propertyDefinition": {
            "type": "object",
            "additionalProperties": { "$ref": "#/definitions/propertyObject" },
            "default": {}
        },
        "propertyObject": {
            "type": "object",
            "properties": {
                "title": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "default": { },
                "type": { "$ref": "#/definitions/simpleTypes" },
                "properties": { "$ref": "#/definitions/propertyDefinition" },
                "items": {
                    "anyOf": [
                        { "$ref": "#/definitions/propertyObject" },
                        { "$ref": "#/definitions/schemaArray" }
                    ],
                    "default": {}
                },
                "reference": {
                    "type": "string",
                    "description": "Defines whether current property is a reference to the actual value of the property",
                    "enum": [
                        "none",
                        "file"
                    ]
                },
                "contentType": {
                    "type": "string",
                    "description": "Defines the content type of the property",
                    "enum": [
                        "default",
                        "uid",
                        "xref",
                        "href",
                        "file",
                        "markdown"
                    ]
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "mergeType": {
                    "type":"string",
                    "description": "Defines how to merge the property",
                    "enum": [
                        "key",
                        "merge",
                        "replace",
                        "ignore"
                    ]
                }
            },
            "patternProperties": {
                "^x_": { }
            }
        },
        "simpleTypes": {
            "enum": [
                "array",
                "boolean",
                "integer",
                "null",
                "number",
                "object",
                "string"
            ]
        }
    },
    "type": "object",
    "properties": {
        "$schema": {
            "type": "string",
            "format": "uri",
            "description": "The version of the schema specification, for example, `https://github.com/dotnet/docfx/v1.0/schema#"
        },
        "version": {
            "type": "string",
            "description": "The version of current schema object"
        },
        "id": {
            "type": "string",
            "description": "It is best practice to include an `id` property as an unique identifier for each schema."
        },
        "title": {
            "type": "string",
            "description": "The title of current schema, `LandingPage`, for example. In DocFX, this value can be used to determine what kind of documents apply to this schema, If not specified, file name of this schema is used."
        },
        "description": {
            "type": "string"
        },
        "type": {
            "type": "string",
            "enum": [
                "object"
            ],
            "description": "The type of the root document model MUST be `object`"
        },
        "default": {},
        "properties": { "$ref": "#/definitions/propertyDefinition" },
        "patternProperties": {
            "^x_": { }
        }
    },
    "default": {}
}

=== dotnet/docfx/test/Microsoft.DocAsCode.Build.SchemaDriven.Tests/TestData/schemas/contextobject.test.schema.json
{
  "$schema": "http://dotnet.github.io/docfx/schemas/v1.0/schema.json#",
  "version": "1.0.0",
  "id": "https://github.com/dotnet/docfx/test/schemas/contextobject.test.schema.json",
  "title": "ContextObject",
  "description": "The test schema for context object",
  "type": "object",
  "properties": {
    "breadcrumb_path": {
      "type": "string",
      "contentType": "href"
    },
    "toc_rel": {
      "type": "string",
      "contentType": "href"
    }
  }
}

=== dotnet/docfx/docs/template/schemas/Dashboard.schema.json
{
    "title": "Dashboard",
    "$schema": "https://dotnet.github.io/docfx/schemas/v1.0/schema.json#",
    "version": "1.0.0",
    "description": "Schema for dashboard",
    "id": "https://github.com/dotnet/docfx/schemas/Dashboard.schema.json",
    "type": "object",
    "properties": {
        "uid": {
            "type": "string",
            "contentType": "uid"
        },
        "title": {
            "type": "string",
            "tags": [
                "localizable"
            ]
        },
        "description": {
            "type": "string",
            "contentType": "markdown",
            "tags": [
                "localizable"
            ]
        },
        "items": {
            "items": {
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "description": {
                        "type": "string",
                        "contentType": "markdown",
                        "tags": [
                            "localizable"
                        ]
                    }
                },
                "type": "object"
            },
            "type": "array"
        }
    }
}

=== dotnet/docfx/test/Microsoft.DocAsCode.Build.SchemaDriven.Tests/TestData/schemas/mref.test.schema.json
{
  "$schema": "http://dotnet.github.io/docfx/schemas/v1.0/schema.json#",
  "version": "1.0.0",
  "id": "https://github.com/dotnet/docfx/test/schemas/contextobject.test.schema.json",
  "title": "ManagedReference",
  "description": "A test schema for simple managed reference",
  "type": "object",
  "properties": {
    "items": {
      "items": {
        "properties": {
          "assemblies": {
            "items": {
              "type": "string"
            },
            "type": "array"
          },
          "children": {
            "items": {
              "type": "string",
              "contentType": "xref"
            },
            "type": "array"
          },
          "commentId": {
            "type": "string"
          },
          "example": {
            "items": {
              "type": "string",
              "contentType": "markdown"
            },
            "type": "array"
          },
          "fullName": {
            "type": "string"
          },
          "id": {
            "type": "string"
          },
          "inheritance": {
            "items": {
              "type": "string",
              "contentType": "xref"
            },
            "type": "array"
          },
          "inheritedMembers": {
            "items": {
              "type": "string",
              "contentType": "xref"
            },
            "type": "array"
          },
          "langs": {
            "items": {
              "type": "string"
            },
            "type": "array"
          },
          "modifiers.csharp": {
            "items": {
              "type": "string"
            },
            "type": "array"
          },
          "modifiers.vb": {
            "items": {
              "type": "string"
            },
            "type": "array"
          },
          "name": {
            "type": "string"
          },
          "nameWithType": {
            "type": "string"
          },
          "namespace": {
            "type": "string",
            "contentType": "xref"
          },
          "parent": {
            "type": "string",
            "contentType": "xref"
          },
          "summary": {
            "type": "string",
            "contentType": "markdown"
          },
          "syntax": {
            "properties": {
              "content": {
                "type": "string"
              },
              "content.vb": {
                "type": "string"
              }
            },
            "type": "object"
          },
          "type": {
            "type": "string"
          },
          "uid": {
            "type": "string",
            "contentType": "uid"
          }
        },
        "type": "object",
        "xrefProperties": [ "name", "commentId", "nameWithType", "fullName", "summary", "extensionMethods/0" ]
      },
      "type": "array"
    },
    "references": {
      "items": {
        "properties": {
          "commentId": {
            "type": "string"
          },
          "fullName": {
            "type": "string"
          },
          "isExternal": {
            "type": "boolean"
          },
          "name": {
            "type": "string"
          },
          "nameWithType": {
            "type": "string"
          },
          "uid": {
            "type": "string"
          }
        },
        "type": "object",
        "xrefProperties": [ "uid", "name", "commentId", "nameWithType", "fullName", "summary", "href" ]
      },
      "type": "array"
    }
  }
}

=== dotnet/docfx/test/Microsoft.DocAsCode.Build.SchemaDriven.Tests/TestData/schemas/fragments.validation.schema.json
{
  "title": "FragmentsValidation",
  "$schema": "https://dotnet.github.io/docfx/schemas/v1.0/schema.json#",
  "version": "1.0.0",
  "description": "The schema for fragments validation",
  "id": "https://github.com/dotnet/docfx/schemas/rest.operationgroup.schema.json",
  "type": "object",
  "properties": {
    "operations": {
      "items": {
        "properties": {
          "summary": {
            "type": "string"
          },
          "description": {
            "type": "string",
            "contentType": "markdown",
            "tags": [
              "editable"
            ]
          },
          "id": {
            "type": "string",
            "mergeType": "key"
          }
        },
        "type": "object"
      },
      "type": "array"
    },
    "author": {
      "description": "service uid",
      "type": "string",
      "tags": [
        "editable"
      ]
    },
    "depot_name": {
      "description": "service uid",
      "type": "string",
      "contentType": "markdown"
    },
    "site_name": {
      "description": "service uid",
      "type": "string"
    },
    "summary": {
      "type": "string",
      "contentType": "markdown",
      "tags": [
        "editable"
      ]
    },
    "description": {
      "type": "string",
      "contentType": "markdown",
      "tags": [
        "localizable"
      ]
    },
    "uid": {
      "contentType": "uid",
      "type": "string"
    }
  }
}
